ssh_port|修改 SSH 端口|scripts/ssh/change-port.sh|bash|
bbr|开启 BBR|scripts/network/bbr.sh|bash|
nginx|安装 Nginx|scripts/app/install-nginx.sh|bash|
xanmod|安装 XanMod x64v3 内核|scripts/system/install-xanmod-kernel.sh|bash|
